2018-12-18 13:59:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.otomoto.pl/osobowe/?page=13> (referer: https://www.otomoto.pl/osobowe/?page=12)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 30, in process_spider_output
    for x in result:
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/databiz206/Marwen/formation/formation/Cars/Cars/spiders/carsspider.py", line 29, in parse
    capacite = car.css('li.offer-item__params-item > span::text').extract()[2]
IndexError: list index out of range
